"""Add height column to mother_profiles

Revision ID: 0d29c18c2d44
Revises: 7a8c47a96aa0
Create Date: 2025-04-06 01:06:43.270551

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0d29c18c2d44'
down_revision = '7a8c47a96aa0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mother_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('height', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mother_profiles', schema=None) as batch_op:
        batch_op.drop_column('height')

    # ### end Alembic commands ###
