"""Add weight, blood pressure, sugar levels, and age to MotherProfile

Revision ID: 7a8c47a96aa0
Revises: c6af9a023871
Create Date: 2025-04-05 19:36:18.587465

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7a8c47a96aa0'
down_revision = 'c6af9a023871'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mother_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('weight', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('blood_pressure', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('sugar_levels', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('age', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mother_profiles', schema=None) as batch_op:
        batch_op.drop_column('age')
        batch_op.drop_column('sugar_levels')
        batch_op.drop_column('blood_pressure')
        batch_op.drop_column('weight')

    # ### end Alembic commands ###
