"""Add trimester and last visit date to MotherProfile

Revision ID: c6af9a023871
Revises: 99059f2b41e5
Create Date: 2025-04-05 18:56:03.218133

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c6af9a023871'
down_revision = '99059f2b41e5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mother_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_visit_date', sa.DateTime(), nullable=True))
        batch_op.alter_column('trimester',
               existing_type=mysql.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('mother_profiles', schema=None) as batch_op:
        batch_op.alter_column('trimester',
               existing_type=sa.String(length=20),
               type_=mysql.INTEGER(),
               existing_nullable=True)
        batch_op.drop_column('last_visit_date')

    # ### end Alembic commands ###
